excluded:
  - Pods
  - InternalPackages/CloudSync/.build
  - InternalPackages/CryptoUtils/.build
  - Carthage
  - TwoFAuthFavIconExporter
  - fastlane
  - Kronos
  - OneTimePassword
analyzer_rules:
  - unused_import
  - unused_private_declaration

opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fatal_error_message
  - first_where
  - identical_operands
  - joined_default_parameter
  - let_var_whitespace
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

disabled_rules:
  - statement_position
  - file_header
  - number_separator
  - todo
  - trailing_comma
  - identifier_name
  - file_name
  - type_body_length
  - function_body_length
  - block_based_kvo
  - force_cast
  - inert_defer
  - implicit_getter
  - no_fallthrough_only
  - line_length
  - cyclomatic_complexity
  - file_length

custom_rules:
  no_objcMembers:
    name: "@objcMembers"
    regex: "@objcMembers"
    message: "Explicitly use @objc on each member you want to expose to Objective-C"
    severity: error
