# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do
  desc "Upload screenshots"
  lane :screenshots do
    snapshot

    deliver(
      overwrite_screenshots: true,
      automatic_release: true,
      skip_binary_upload: true,
      skip_metadata: true,
      skip_app_version_update: true
    )
  end

  desc "Upload beta"
  lane :beta do
    ensure_git_status_clean
    increment_build_number
    build_app

    upload_to_testflight(
      skip_submission: true,
      skip_waiting_for_build_processing: true
    )

    clean_build_artifacts

    git_commit(
      path: ["*.plist", "TwoFAuth.xcodeproj/project.pbxproj"],
      message: "Bump build number to #{get_build_number}"
    )

    add_git_tag(
      tag: "build/#{get_build_number}"
    )
  end
end
