name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Fetch submodules
      run: git submodule update --init

    - name: Run Tests
      run: set -o pipefail && xcodebuild clean test -project TwoFAuth.xcodeproj -scheme TwoFAuth -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' ONLY_ACTIVE_ARCH=NO | xcpretty -c
